'use client';

import React from 'react';
import dynamic from 'next/dynamic';

// Dynamically import the orderbook component to avoid SSR issues with WebSocket
const Orderbook = dynamic(() => import('./components/Orderbook'), { ssr: false });

export default function Home() {
  return (
    <main className="min-h-screen bg-gray-800 py-10">
      <div className="container mx-auto px-4">
        <header className="mb-10 text-center">
          <h1 className="text-3xl font-bold text-white mb-2">Market Data Dissemination Simulator</h1>
          <p className="text-gray-300 mb-4">
            Real-time order book visualization using WebSockets
          </p>
          <div className="bg-blue-900/50 border border-blue-700 text-blue-100 p-3 rounded-md mx-auto max-w-2xl text-sm">
            <p><span className="font-semibold">Data Source:</span> This is simulated market data generated by the API server. Not real market data.</p>
            <p className="mt-1">Updates occur every 1-3 seconds with randomized price levels to demonstrate orderbook visualization concepts.</p>
          </div>
        </header>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <Orderbook instrumentId={1} symbol="AAPL" depth={10} />
          <Orderbook instrumentId={2} symbol="MSFT" depth={5} />
        </div>

        <footer className="mt-10 text-center text-gray-400 text-sm">
          <p>Market Data Dissemination Simulator - Demonstrating middleware concepts with gRPC</p>
        </footer>
      </div>
    </main>
  );
}
